name: dlvr-project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - simpleitk
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - pandas
  - ipykernel
  - pip
  - pip:
    - nibabel