name: dlvr-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - tensorflow
  - keras
  - numpy
  - pillow
  - matplotlib
  - opencv
  - jupyter
  - pip
  - pip:
    - youtube_dl